### ISSUE TITLE
Crash: kpt live preview fails for ResourceGroup

### ISSUE THREAD

**Issue by seans3** [GoogleContainerTools/kpt#1222]
* kpt live preview crashes if run before anything has been applied.
* `export RESOURCE_GROUP_INVENTORY=1`
* Happens when ConfigMap is inventory object.

```
$ kpt live preview ~/testdata/testdata-namespace-1
namespace/test-namespace created (preview)
pod/pod-b created (preview)
pod/pod-a created (preview)
pod/pod-c created (preview)
4 resource(s) applied. 4 created, 0 unchanged, 0 configured (preview)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16f78e3]

goroutine 172 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetKind(...)
	/home/sean/go/pkg/mod/k8s.io/apimachinery@v0.18.10/pkg/apis/meta/v1/unstructured/unstructured.go:226
github.com/GoogleContainerTools/kpt/pkg/live.inventoryWrapperFunc(0x0, 0xc000759608, 0x0)
	/home/sean/go/src/github.com/GoogleContainerTools/kpt/pkg/live/dual-delegating-provider.go:48 +0x43
sigs.k8s.io/cli-utils/pkg/inventory.(*ClusterInventoryClient).Replace(0xc000a9c2a0, 0x1d3f560, 0xc0027fc9a0, 0xc00065a000, 0x4, 0x4, 0x0, 0x0)
	/home/sean/go/pkg/mod/sigs.k8s.io/cli-utils@v0.22.0/pkg/inventory/inventory-client.go:166 +0x17f
sigs.k8s.io/cli-utils/pkg/apply/prune.(*PruneOptions).Prune(0xc0006afe00, 0x1d3f560, 0xc0027fc9a0, 0xc0027fc980, 0x4, 0x4, 0xc003196b10, 0xc000a98540, 0x1, 0x1ada852, ...)
	/home/sean/go/pkg/mod/sigs.k8s.io/cli-utils@v0.22.0/pkg/apply/prune/prune.go:162 +0x687
sigs.k8s.io/cli-utils/pkg/apply/task.(*PruneTask).Start.func1(0xc002920cc0, 0xc002772aa0)
	/home/sean/go/pkg/mod/sigs.k8s.io/cli-utils@v0.22.0/pkg/apply/task/prune_task.go:33 +0xab
created by sigs.k8s.io/cli-utils/pkg/apply/task.(*PruneTask).Start
	/home/sean/go/pkg/mod/sigs.k8s.io/cli-utils@v0.22.0/pkg/apply/task/prune_task.go:31 +0x49
```

**Comment by seans3** [comment]
More data on crash:
```
$ tree ~/testdata/testdata-namespace-1
/home/sean/testdata/testdata-namespace-1
├── inventory-template.yaml
├── Kptfile
├── namespace.yaml
├── pod-a.yaml
├── pod-b.yaml
└── pod-c.yaml

0 directories, 6 files
sean@ryzen:~/go/src/github.com/GoogleContainerTools/kpt$ cat ~/testdata/testdata-namespace-1/inventory-template.yaml 
# NOTE: auto-generated. Some fields should NOT be modified.
# Date: 2020-11-11 23:57:35 PST
#
# Contains the "inventory object" template ConfigMap.
# When this object is applied, it is handled specially,
# storing the metadata of all the other objects applied.
# This object and its stored inventory is subsequently
# used to calculate the set of objects to automatically
# delete (prune), when an object is omitted from further
# applies. When applied, this "inventory object" is also
# used to identify the entire set of objects to delete.
#
# NOTE: The name of this inventory template file
# does NOT have any impact on group-related functionality
# such as deletion or pruning.
#
apiVersion: v1
kind: ConfigMap
metadata:
  # DANGER: Do not change the inventory object namespace.
  # Changing the namespace will cause a loss of continuity
  # with previously applied grouped objects. Set deletion
  # and pruning functionality will be impaired.
  namespace: test-namespace
  # NOTE: The name of the inventory object does NOT have
  # any impact on group-related functionality such as
  # deletion or pruning.
  name: inventory-22337953
  labels:
    # DANGER: Do not change the value of this label.
    # Changing this value will cause a loss of continuity
    # with previously applied grouped objects. Set deletion
    # and pruning functionality will be impaired.
    cli-utils.sigs.k8s.io/inventory-id: d9a460f3-0ce3-4675-9acb-c07910a14741
```

**Comment by seans3** [comment]
Fixed with: https://github.com/kubernetes-sigs/cli-utils/pull/280

Closing
