### ISSUE TITLE
kpt cfg set panics when not provided enough arguments

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#1593]
### Expected behavior
If I don't specify enough arguments, a friendly error message is returned

### Actual behavior
Running `kpt cfg set` with insufficient arguments (or an unset setter value) yields a panic:

```
$ kpt cfg set landing-zone/ billing-account-id 
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
sigs.k8s.io/kustomize/cmd/config/internal/commands.(*SetRunner).preRunE(0xc00040cc80, 0xc0004d02c0, 0xc00000d200, 0x2, 0x2, 0x0, 0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/cmd/config@v0.9.5/internal/commands/cmdset.go:78 +0x331
github.com/spf13/cobra.(*Command).execute(0xc0004d02c0, 0xc00000d1a0, 0x2, 0x2, 0xc0004d02c0, 0xc00000d1a0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:831 +0x530
github.com/spf13/cobra.(*Command).ExecuteC(0xc00043e2c0, 0x33cb9e0, 0xc00006a778, 0xc000549f78)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /workspace/kpt/main.go:37 +0x65
```

### Information
v0.38.1

**Comment by phanimarupaka** [comment]
PR https://github.com/kubernetes-sigs/kustomize/pull/3748
