### ISSUE TITLE
panic on missed argument

### ISSUE THREAD

**Issue by noroutine** [GoogleContainerTools/kpt#1771]
### Expected behavior

```
error: unable to find "Kptfile" in package "image-tag"
```

### Actual behavior

```
✦ ❯ kpt cfg set image-tag v0.1.11
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
sigs.k8s.io/kustomize/cmd/config/internal/commands.(*SetRunner).preRunE(0xc0007d2780, 0xc000839600, 0xc0001c2640, 0x2, 0x2, 0x0, 0x0)
	sigs.k8s.io/kustomize/cmd/config@v0.9.9/internal/commands/cmdset.go:78 +0x331
github.com/spf13/cobra.(*Command).execute(0xc000839600, 0xc0001c2600, 0x2, 0x2, 0xc000839600, 0xc0001c2600)
	github.com/spf13/cobra@v1.1.1/command.go:839 +0x523
github.com/spf13/cobra.(*Command).ExecuteC(0xc000028b00, 0x200000003, 0xc000000180, 0xc00082ff78)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	github.com/GoogleContainerTools/kpt/main.go:37 +0x65
```
### Information

Accidentally missed directory argument and got panic

Kpt 0.39.1

### Steps to reproduce the behavior

Just as is

```
kpt cfg set please explode
```

**Comment by runewake2** [comment]
Hi, thanks for reporting this. Could you try running this with [kpt v0.39.2](https://github.com/GoogleContainerTools/kpt/releases/tag/v0.39.2) and let us know if this is still occurring? I no longer see this behavior in that version. This is what I am seeing on version 0.39.2:

```sh
$ kpt cfg set image-tag v0.1.11
error: value must be provided either from flag or arg
```

**Comment by noroutine** [comment]
Hi @runewake2 

Confirm it is gone in v0.39.2 👌
