### ISSUE TITLE
TS SDK labeling example doesn't work

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#2067]
While [trying out TS SDK](https://kpt.dev/book/05-developing-functions/04-developing-in-Typescript), exploring demo-examples, ran into following issue with running labeling demo.

```
$ kpt fn source $CONFIGS|node dist/label_namespace_run.js -d label_name=color -d label_value=orange
....../kpt-functions-sdk/ts/demo-functions/node_modules/kpt-functions/dist/src/io.js:26
console = new console.Console(process.stderr, process.stderr);
        ^

TypeError: Cannot set property console of #<Object> which has only a getter
    at Object.<anonymous> (/...../fishfood-05-20/kpt-functions-sdk/ts/demo-functions/node_modules/kpt-functions/dist/src/io.js:26:9)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/...../kpt-functions-sdk/ts/demo-functions/node_modules/kpt-functions/dist/index.js:29:14)
    at Module._compile (module.js:643:30)

```

**Comment by mikebz** [comment]
should we close this?

**Comment by droot** [comment]
I think it's something to do with my node setup, so closing this for now.
