### ISSUE TITLE
Porch server crashed due to `send on closed channel`

### ISSUE THREAD

**Issue by zhaohua-jiang** [GoogleContainerTools/kpt#3663]
### Expected behavior

Porch server doesn't crash and works normally.

### Actual behavior

Porch server crashed due to `send on closed channel`

### Information

Environment: GKE cluster v1.23.8-gke.1900

Porch server version: v0.0.12:  gcr.io/kpt-dev/porch-server:v0.0.12

Porch server pod log:

```
...
I1117 05:59:20.719578       1 watch.go:219] sending watch event {MODIFIED 0xc000283a00}
I1117 05:59:20.724793       1 watch.go:219] sending watch event {MODIFIED 0xc000283c00}
W1117 05:59:20.740362       1 watch.go:98] sending error to watch stream
I1117 05:59:20.748253       1 watch.go:219] sending watch event {MODIFIED 0xc00241ae00}
panic: send on closed channel

goroutine 1067 [running]:
github.com/GoogleContainerTools/kpt/porch/pkg/registry/porch.(*watcher).sendWatchEvent(0xc00007f600, {{0x4112848?, 0xc00206f340?}, {0x451b8b0?, 0xc00241ae00?}})
	/go/src/github.com/GoogleContainerTools/kpt/porch/pkg/registry/porch/watch.go:220 +0x15f
github.com/GoogleContainerTools/kpt/porch/pkg/registry/porch.(*watcher).listAndWatchInner.func3({0x4112848, 0x8}, {{0x45423c8, 0xc000bd6858}, {{0xc0015105c0, 0x38}, {0xc0015c1986, 0x7}, 0xc001725a70, 0x0}})
	/go/src/github.com/GoogleContainerTools/kpt/porch/pkg/registry/porch/watch.go:200 +0xcf
github.com/GoogleContainerTools/kpt/porch/pkg/registry/porch.(*watcher).OnPackageRevisionChange(0xc000000001?, {0x4112848?, 0xc0003c6310?}, {0x45423c8?, 0xc000bd6858?}, {{0xc0015105c0, 0x38}, {0xc0015c1986, 0x7}, 0xc001725a70, ...})
	/go/src/github.com/GoogleContainerTools/kpt/porch/pkg/registry/porch/watch.go:228 +0x1c8
github.com/GoogleContainerTools/kpt/porch/pkg/engine.(*watcherManager).NotifyPackageRevisionChange(0xc00073afa0, {0x4112848, 0x8}, {0x45423c8, 0xc000bd6858}, {{0xc0015105c0, 0x38}, {0xc0015c1986, 0x7}, 0xc001725a70, ...})
	/go/src/github.com/GoogleContainerTools/kpt/porch/pkg/engine/watchermanager.go:105 +0x29e
github.com/GoogleContainerTools/kpt/porch/pkg/cache.(*cachedRepository).refreshAllCachedPackages(0xc000f8a000, {0x4538a30, 0xc001725290})
	/go/src/github.com/GoogleContainerTools/kpt/porch/pkg/cache/repository.go:453 +0x9c4
github.com/GoogleContainerTools/kpt/porch/pkg/cache.(*cachedRepository).getCachedPackages(0x29b6465?, {0x4538a30?, 0xc001725290?}, 0xc0?)
	/go/src/github.com/GoogleContainerTools/kpt/porch/pkg/cache/repository.go:153 +0x52
github.com/GoogleContainerTools/kpt/porch/pkg/cache.(*cachedRepository).getPackageRevisions(0x2?, {0x4538a30?, 0xc001725290?}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...)
	/go/src/github.com/GoogleContainerTools/kpt/porch/pkg/cache/repository.go:119 +0xf9
github.com/GoogleContainerTools/kpt/porch/pkg/cache.(*cachedRepository).pollOnce(0xc000f8a000, {0x4538988, 0xc0011e4b40})
	/go/src/github.com/GoogleContainerTools/kpt/porch/pkg/cache/repository.go:325 +0x228
github.com/GoogleContainerTools/kpt/porch/pkg/cache.(*cachedRepository).pollForever(0x5d998c0?, {0x4538988, 0xc0011e4b40})
	/go/src/github.com/GoogleContainerTools/kpt/porch/pkg/cache/repository.go:311 +0x71
created by github.com/GoogleContainerTools/kpt/porch/pkg/cache.newRepository
	/go/src/github.com/GoogleContainerTools/kpt/porch/pkg/cache/repository.go:83 +0x1f9
```
### Steps to reproduce the behavior

it's happened very very rarely, I found this issue only once in the past two weeks after upgrading to porch v0.0.12

**Comment by mortent** [comment]
Thanks for reporting this. We will take a look at it.
