### ISSUE TITLE
WASM function error messages are unusable

### ISSUE THREAD

**Issue by wleese** [GoogleContainerTools/kpt#3763]
When a starlark function or apply-replacements function, compiled to yaml throw an error due to a missing or incorrect value, the error messages provide almost no clues as to what's going wrong.
It seems like error messages are being swallowed and replaced by generic wasm runtime errors.

```
[RUNNING] WASM "eu.gcr.io/bolcom-stg-mvpbb8-infra-fc1/starlark:unstable"
I0128 09:32:00.548368    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.548389    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.549235    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.553937    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.553981    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.559820    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.560444    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.568890    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.586809    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.598853    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.598865    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.613356    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.613369    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.672876    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.672894    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.689034    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.689042    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
I0128 09:32:00.700646    7965 log.go:195] ERROR: syscall/js.stringVal: bad address
I0128 09:32:00.701895    7965 log.go:195] ERROR: runtime.resetMemoryDataView NOT IMPLEMENTED
[FAIL] "eu.gcr.io/bolcom-stg-mvpbb8-infra-fc1/starlark:unstable" in 100ms
Error: wrong Node Kind for  expected: MappingNode was ScalarNode: value: {s(float64=5.565e-320}
```

Here's a simple function:

```
apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: 
  name: apply-team-name-to-iampolicymember
  annotations:
    config.kubernetes.io/local-config: "true"
params:
  team:
source: |
  def constructResources(resources, name):
    for r in resources:
      if r["kind"] == "IAMPolicyMember" and r["metadata"]["name"] == "team-viewer-all":
        r["spec"]["member"] = "group:" + team + "@bol.com"

  team = ctx.resource_list["functionConfig"]["params"]["team"]
  constructResources(ctx.resource_list["items"], team)
```

If you look carefully you see that `params.team` is empty/null, but we blindly pass it into our method `constructResources` and try to use it.
Running `kpt fn render . --allow-alpha-wasm` with our WASM compiled starlark function results in:

```
panic: ValueOf: invalid value

goroutine 6 [running]:
syscall/js.ValueOf({0xf0c60, 0x1709c60})
	/usr/local/go/src/syscall/js/js.go:208 +0xf7
syscall/js.Value.Set({{}, 0x7ff8000100000012, 0x15b84f0}, {0x1fbbd4, 0x6}, {0xf0c60, 0x1709c60})
	/usr/local/go/src/syscall/js/js.go:303 +0x8
syscall/js.handleEvent()
	/usr/local/go/src/syscall/js/func.go:95 +0x27
[FAIL] "eu.gcr.io/bolcom-stg-mvpbb8-infra-fc1/starlark:unstable" in 0s
Error: wrong Node Kind for  expected: MappingNode was ScalarNode: value: {s(<nil>}
```

When we run the docker based function we get something completely different:

```
Package "kpt":
[RUNNING] "gcr.io/kpt-fn/starlark:v0.4.3"
[FAIL] "gcr.io/kpt-fn/starlark:v0.4.3" in 600ms
  Results:
    [error]: unknown binary op: string + NoneType
  Stderr:
    "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"
    "failed to evaluate function: error: function failure"
  Exit code: 1
```

**Comment by natasha41575** [comment]
Thank you for the detailed bug report! I agree that the example errors you've provided from the wasm functions are not helpful, and should be improved. This may be a good first issue if anyone reading this is looking to contribute to the kpt project.
