### ISSUE TITLE
WASM functions provide useless/misleading error messages

### ISSUE THREAD

**Issue by wleese** [GoogleContainerTools/kpt#3822]
With this setup:

Kptfile
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: kpt
  annotations:
    config.kubernetes.io/local-config: "true"
info:
  description: this package provides the parent package for your application
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/starlark:v0.4.3
      configPath: starlarkconfig.yaml
```
resources.yaml
```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: bucket-read-write-by-service-account-diogotuesday274
  namespace: bb8-tuesdayds
```
starlarkconfig.yaml
```
apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: apply-team-name-to-iampolicymember
source: |
  team = ctx.resource_list["functionConfig"]["params"]["team"]
```

A `kpt fn render . --allow-alpha-wasm` results in the following error:

```
Package "kpt2":
[RUNNING] WASM "eu.gcr.io/xxx/starlark:unstable"
panic: ValueOf: invalid value

goroutine 6 [running]:
syscall/js.ValueOf({0xf0c60, 0x165d4b0})
	/usr/local/go/src/syscall/js/js.go:208 +0xf7
syscall/js.Value.Set({{}, 0x7ff8000100000012, 0x15ba4f0}, {0x1fbbd4, 0x6}, {0xf0c60, 0x165d4b0})
	/usr/local/go/src/syscall/js/js.go:303 +0x8
syscall/js.handleEvent()
	/usr/local/go/src/syscall/js/func.go:95 +0x27
[FAIL] "eu.gcr.io/xxx/starlark:unstable" in 0s
Error: invalid resource list output from wasm library; got "s(<nil>"
 %!q(<nil>)
```

This error is not usable.

Contrast this with running the same setup, with the docker version of the starlark function:

```
Package "kpt2":
[RUNNING] "gcr.io/kpt-fn/starlark:v0.4.3"
[FAIL] "gcr.io/kpt-fn/starlark:v0.4.3" in 400ms
  Results:
    [error]: key "params" not in dict
  Stderr:
    "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"
    "failed to evaluate function: error: function failure"
  Exit code: 1
```

The error `key "params" not in dict` is no where to be found in the wasm versions error message.

**Comment by wleese** [comment]
Correct me if I'm wrong, but it would seem that when porting the functions to wasm, there are some issues in the used boilerplate that causes these terrible error messages. The first one I'm fairly confident on is mixing return types:

```

func resourceListProcessorWrapper() js.Func {
	// TODO: figure out a better way to surface a golang error to JS environment.
	// Currently error is surfaced as a string.
	jsonFunc := js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		if len(args) != 1 {
			return "Invalid number of arguments passed"
		}
		input := args[0].String()
		applied, err := executeStarlark([]byte(input))
		if err != nil {
			return fmt.Errorf("unable to process resource list:", err.Error())
		}
		return string(applied)
	})
	return jsonFunc
}
```

While our `jsonFunc` can return `interface{}`, it seems that we currently don't tolerate the situation when we return an `Error`, resulting in `panic: ValueOf: invalid value`. Instead, if we return the `Error` as a string, things work a bit more smoothly:

```
Package "kpt2":
[RUNNING] WASM "starlark-wasm"
[FAIL] "starlark-wasm" in 0s
Error: &{unable to process resource list:
error: function failure}
```

Cool! So while we don't have the real error `key "params" not in dict`, we no longer get a weird panic (from wasmtime?) and clearly get the traditionally `stderr` output of our function `function failure`.
Next step would be extracting the real error, which I'm guessing needs to be retrieved via `resourceList`.

**Comment by wleese** [comment]
Returning multiple values when using `wasmexec` doesn't seem possible. Working around the issue by introducing a function specifically to retrieve `resourceList`, which kpt can then use to extract any errors from `results`.

```
func run() error {
	resourceList := ""
	// Register js function processResourceList to the globals.
	js.Global().Set("processResourceList", resourceListProcessorWrapper(&resourceList))
	// Provide a second function that serves purely to also return the resourceList,
	// in case of the above function failihng.
	js.Global().Set("processResourceListErrors", resourceListProcessorErrors(&resourceList))
	// We need to ensure that the Go program is running when JavaScript calls it.
	// Otherwise, it will complain the Go program has already exited.
	<-make(chan bool)
	return nil
}

func executeStarlark(input []byte) ([]byte, error) {
	return fn.Run(fn.ResourceListProcessorFunc(starlark.Process), []byte(input))
}

func resourceListProcessorWrapper(resourceList *string) js.Func {
	jsonFunc := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) != 1 {
			return "Invalid number of arguments passed"
		}
		input := args[0].String()
		applied, err := executeStarlark([]byte(input))
		if err != nil {
			*resourceList = string(applied)
			return "unable to process resource list: " + err.Error()
		}
		*resourceList = string(applied)
		return string(applied)
	})

	return jsonFunc
}

func resourceListProcessorErrors(resourceList *string) js.Func {
	jsonFunc := js.FuncOf(func(this js.Value, args []js.Value) any {
		return *resourceList
	})
	return jsonFunc
}
```

Alternatively, the second function I introduced could return the actual error message.
That said, I think that's cleaner, so I'll iterate on that approach.

**Comment by wleese** [comment]
Thanks again!
