### ISSUE TITLE
question - get values

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/kpt#788]
Hi,
is it possible to get certain values analog to setter methods?
regards
Marco

**Comment by prachirp** [comment]
Hey Marco, you can use `kpt cfg grep` to get the field values on resources. Check out https://googlecontainertools.github.io/kpt/reference/cfg/grep/

**Comment by MarcoSchaar** [comment]
Hej @prachirp 
thanks for pointing to grep 

gave a try to check the help for this command. 
basically I'm trying to fetch e.g. an image tag into a variable.

running kpt on windows

```bash
 kpt help cfg grep
panic: unable to redefine 'v' shorthand in "grep" flagset: it's already used for "invert-match" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000438b00, 0xc000369860)
        /go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:874 +0x6de
github.com/spf13/pflag.(*FlagSet).AddFlagSet.func1(0xc000369860)
        /go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:887 +0xaf
github.com/spf13/pflag.(*FlagSet).VisitAll(0xc001634e00, 0xc001833c08)
        /go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0x9b
github.com/spf13/pflag.(*FlagSet).AddFlagSet(0xc000438b00, 0xc001634e00)
github.com/spf13/cobra.(*Command).mergePersistentFlags(0xc0003b82c0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:1612 +0x97
github.com/spf13/cobra.(*Command).InitDefaultHelpFlag(0xc0003b82c0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:1004 +0x36
github.com/spf13/cobra.(*Command).InitDefaultHelpCmd.func1(0xc0000cc2c0, 0xc0004605c0, 0x2, 0x2)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:1062 +0x144
github.com/spf13/cobra.(*Command).execute(0xc0000cc2c0, 0xc000460560, 0x2, 0x2, 0xc0000cc2c0, 0xc000460560)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0xc00008a840, 0x43e741, 0x28719e0, 0xc00006bf50)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /workspace/main.go:37 +0x6f
```

**Comment by prachirp** [comment]
Hey @MarcoSchaar thanks for following up! I made a fix for the error you ran into. In the meantime you can find the grep help docs at https://github.com/GoogleContainerTools/kpt/blob/4be756ad01b0f7651e8fb6b7fec88c0478e0972e/internal/docs/generated/cfgdocs/docs.go#L237
