### ISSUE TITLE
homebrew installation fails on macOS 11 (Big Sur)

### ISSUE THREAD

**Issue by salaxander** [GoogleContainerTools/kpt#962]
I'm running the beta version of macOS 11, and have been running into issue trying to `brew upgrade` to the latest version. Wanted to file this issue early since there's likely plenty of time before Big Sur exits beta :)

```
==> Upgrading 1 outdated package:
googlecontainertools/kpt/kpt 0.32.0 -> 0.33.0
==> Upgrading googlecontainertools/kpt/kpt 0.32.0 -> 0.33.0
==> Downloading https://github.com/GoogleContainerTools/kpt/archive/v0.33.0.tar.
Already downloaded: /Users/xander/Library/Caches/Homebrew/downloads/ac1b2a55ace325dc4b88fa6472234f6240ba15cd90ad89237df2812f6c8f5011--kpt-0.33.0.tar.gz
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
```

**Comment by mortent** [comment]
@salaxander Thanks for reporting this. We don't have access to Big Sur yet, so we haven't seen this issue.

The error seems to suggest that it is the XCode Command Line Tools that are out-of-date. Have you tried to update XCode and the CLT?

**Comment by vmanot** [comment]
This has resurfaced with the release of Xcode 12GM.

**Comment by dive** [comment]
Yep, the same problem. Xcode 12 GM and Command Line Tools for Xcode 12 does not have macOS 11 SDK:

```
ls -l ./Xcode_12_GM_seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
total 0
drwxr-xr-x  5 dive  staff   160B 16 Sep 11:48 .
drwxr-xr-x  6 dive  staff   192B  9 Sep 19:22 ..
drwxr-xr-x  4 dive  staff   128B 10 Aug 18:36 DriverKit19.0.sdk
drwxr-xr-x  8 dive  staff   256B 10 Aug 18:36 MacOSX.sdk
lrwxr-xr-x  1 dive  staff    10B 16 Sep 11:47 MacOSX10.15.sdk -> MacOSX.sdk
```

**Comment by grischa** [comment]
I have the same issue with other packages that are not bottled.

It seems that the stable release of Xcode 12 only supports MacOS Catalina/10.15 SDKs
```
% ls -l /Library/Developer/CommandLineTools/SDKs
total 0
lrwxr-xr-x  1 root  wheel   15 17 Sep 22:50 MacOSX.sdk -> MacOSX10.15.sdk
drwxr-xr-x  8 root  wheel  256 17 Sep 22:50 MacOSX10.15.sdk
```
So, either try the new Xcode beta, or wait, I guess

**Comment by rbugajewski** [comment]
> So, either try the new Xcode beta, or wait, I guess

Xcode 12.2 beta (12B5018i) has the same issue. Downloading & installing the CLTs didn’t solve the underlying error message.

**Comment by thatguyibdev** [comment]
Brew is being updated to support MacOS Big Sur. You can see the progress at their git page here. [Their issues page](https://github.com/Homebrew/brew/issues/7857)

**Comment by rknall** [comment]
> Brew is being updated to support MacOS Big Sur. You can see the progress at their git page here. [Their issues page](https://github.com/Homebrew/brew/issues/7857)

Not the same thing. It had been working in the past. It really seems, that we have a situation atm, which does not allow for development on the DTK if not directly in the XCode 12.2 beta

**Comment by mariusk** [comment]
I've got a few Big Sur systems by now, and Homebrew worked on some of them, but not on others. I've tried various combinations of installing Xcode 12, Xcode 12.2 beta and command line tools packages. There is no command line tools package for the 12.2 beta yet, so haven't tested that of course. In the end I believe command line tools 12 is enough, with the proper symlinks in place. I took an image of symlinks from a Big Sur system where building emacs from source worked, and tried putting the same symlinks in place where it did not. When it did not work, it was because the configure script reported that the C compiler was not working. I'll share screenshot with the symlinks from the system that worked (and which fixed one system where it did not, prior to adding similar symlinks):
![image](https://user-images.githubusercontent.com/218612/94466134-3dad1000-01c1-11eb-89cc-e50f75776f8b.png)
I'm not claming this is a solution, or a good solution, but if it either helps somebody else in getting Homebrew working again, or if it help diagnose the underlying cause, that's a good thing at least.

**Comment by rknall** [comment]
You could use the dev-kit included in XCode 12.2? At least it works for me on non-brew stuff. Still issues getting brew working correctly again after upgrading to beta 8

```
rknall@MacDevKit-2 wget-1.20 % xcode-select --print-path
/Applications/Xcode-beta.app/Contents/Developer
```

**Comment by mariusk** [comment]
Re: Xcode 12.2 beta - could be. I think it's 100 gigabytes unpacked or something. One of my old iMacs has 120 gb, so it's easier said than done. But I believe I've tried the 12.2 beta without success on another machine. But could be I messed something up.

**Comment by darrarski** [comment]
> > So, either try the new Xcode beta, or wait, I guess
> 
> Xcode 12.2 beta (12B5018i) has the same issue. Downloading & installing the CLTs didn’t solve the underlying error message.

Command Line Tools for Xcode 12.2 beta 2 contains required SDK (`MacOSX11.0.sdk`).

> Re: Xcode 12.2 beta - could be. I think it's 100 gigabytes unpacked or something. One of my old iMacs has 120 gb, so it's easier said than done. But I believe I've tried the 12.2 beta without success on another machine. But could be I messed something up.

You don't have to download the whole Xcode app, just "Command Line Tools for Xcode 12.2 beta 2" which can be found on https://developer.apple.com/download/more/ - it's only ~450MB. 

I just installed the mentioned command line tools and `brew doctor` no longer shows warning about missing CLT. I also manage to install some stuff using brew without an issue.

**Comment by mariusk** [comment]
> You don't have to download the whole Xcode app, just "Command Line Tools for Xcode 12.2 beta 2" which can be found on https://developer.apple.com/download/more/ - it's only ~450MB.

Yeah, it was literally made available just now. I hope that finally takes care of the issues for people who are not able to work around it with symlinks and/or old installation of stuff.

**Comment by pavankjadda** [comment]
> > You don't have to download the whole Xcode app, just "Command Line Tools for Xcode 12.2 beta 2" which can be found on https://developer.apple.com/download/more/ - it's only ~450MB.
> 
> Yeah, it was literally made available just now. I hope that finally takes care of the issues for people who are not able to work around it with symlinks and/or old installation of stuff.

Let me know if this works

**Comment by mariusk** [comment]
I just tested the command line tools 12.2 beta on one of the systems that refused to build emacs from source as described, and I'm happy to report that seems to have solved the issue.

**Comment by rknall** [comment]
> I just tested the command line tools 12.2 beta on one of the systems that refused to build emacs from source as described, and I'm happy to report that seems to have solved the issue.

Can you execute the builded binaries as well? Building works on 12.2, execution heavily depends on what libraries you are using

**Comment by mariusk** [comment]
> Can you execute the builded binaries as well? Building works on 12.2, execution heavily depends on what libraries you are using

Yes, I rebuilt Emacs from scratch and can confirm it's working fine.

**Comment by funfake** [comment]
I can confirm that just by installing the Command Line Tools for Xcode 12.2, it is working fine now. Thanks guys for your help.

**Comment by igor9silva** [comment]
I can confirm as well. 

I'm using Xcode 12 stable. After installing "Command Line Tools for Xcode 12.2 beta **2**", `brew` worked as expected.

**Comment by abc101** [comment]
> I can confirm as well.
> 
> I'm using Xcode 12 stable. After installing "Command Line Tools for Xcode 12.2 beta **3**", `brew` worked as expected.

It works for me.

`
$ softwareupdate --list
Software Update Tool

Finding available software
Software Update found the following new or updated software:
* Label: Command Line Tools beta 3 for Xcode-12.2
	Title: Command Line Tools beta 3 for Xcode, Version: 12.2, Size: 440919K, Recommended: YES,
$ softwareupdate -i "Command Line Tools beta 3 for Xcode-12.2"
`

**Comment by MarlonJD** [comment]
> I can confirm as well.
> 
> I'm using Xcode 12 stable. After installing "Command Line Tools for Xcode 12.2 beta **3**", `brew` worked as expected.

Thank you so much. ıt's time saver. Works perfectly. 
Here is the page: https://developer.apple.com/download/more/

**Comment by pallavi10aggarwal** [comment]
> I can confirm as well.
> 
> I'm using Xcode 12 stable. After installing "Command Line Tools for Xcode 12.2 beta **3**", `brew` worked as expected.
 bro did it worked with Xcode 12.1 ?

**Comment by pallavi10aggarwal** [comment]
Hi , I am getting this error when I try to update pods for my project  I am on Xcode 12.1 , macOS Bigsur

viza@ viza-MacBook-Pro EMGuidanceMerge % pod update
/Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin18/digest/sha2.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (LoadError)
  Referenced from: /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin18/digest/sha2.bundle
  Reason: image not found - /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin18/digest/sha2.bundle
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/digest/sha2.rb:14:in `<top (required)>'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:1:in `<top (required)>'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/sources_manager.rb:5:in `<top (required)>'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/core_overrides.rb:1:in `<top (required)>'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods.rb:75:in `<module:Pod>'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods.rb:17:in `<top (required)>'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/bin/pod:36:in `<top (required)>'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
	from /Users/viza/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
	from /Users/viza/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:24:in `eval'
	from /Users/viza/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:24:in `<main>'
viza@ viza-MacBook-Pro EMGuidanceMerge %

**Comment by SiM07** [comment]
After update to Big Sur, when I run `brew upgrade` I had an error when install python 3.8.

```
[...]
Warning: Building python@3.8 from source:
  The bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install

==> Downloading https://files.pythonhosted.org/packages/a7/e0/30642b9c2df516506d
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/0b/f5/be8e741434a4bf4ce5
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/83/72/611c121b6bd15479cb
######################################################################## 100.0%
==> Downloading https://www.python.org/ftp/python/3.8.6/Python-3.8.6.tar.xz
######################################################################## 100.0%
Error: Your Xcode does not support macOS 11.0.
It is either outdated or was modified.
Please update your Xcode or delete it if no updates are available.
```

To Fixed it, I install `Command Line Tools for XCode 12.2` manually from https://developer.apple.com/download/more/?=for%20Xcode

It's ok after.

**Comment by wxz896446511** [comment]
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Error: An exception occurred within a child process:
  SystemExit: exit

**Comment by Jonnaz** [comment]
I have just tested the`Command Line Tools for Xcode 12.3 beta` with success:
[Apple Developer Portal](https://developer.apple.com/download/more/?=Command%20Line%20Tools%20for%20Xcode%2012.3%20beta)

**Comment by fabb** [comment]
Another solution:
```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

Thanks `brew doctor` for this hint.

**Comment by Jonnaz** [comment]
> Another solution:
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> sudo xcode-select --install
> ```
> 
> Thanks `brew doctor` for this hint.

I had tried that.
I would imagine it depends on the version of Xcode installed, I didn't have success with 12.2 but I did with the 12.3 CLT.

Not arguing, just noting the solution may not work for all.

**Comment by Deaniell61** [comment]
> > > So, either try the new Xcode beta, or wait, I guess
> > 
> > 
> > Xcode 12.2 beta (12B5018i) has the same issue. Downloading & installing the CLTs didn’t solve the underlying error message.
> 
> Command Line Tools for Xcode 12.2 beta 2 contains required SDK (`MacOSX11.0.sdk`).
> 
> > Re: Xcode 12.2 beta - could be. I think it's 100 gigabytes unpacked or something. One of my old iMacs has 120 gb, so it's easier said than done. But I believe I've tried the 12.2 beta without success on another machine. But could be I messed something up.
> 
> You don't have to download the whole Xcode app, just "Command Line Tools for Xcode 12.2 beta 2" which can be found on https://developer.apple.com/download/more/ - it's only ~450MB.
> 
> I just installed the mentioned command line tools and `brew doctor` no longer shows warning about missing CLT. I also manage to install some stuff using brew without an issue.

THIS WORKS FOR ME! I install Command_Line_Tools_for_Xcode_12.2

**Comment by Lonor** [comment]
> Another solution:
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> sudo xcode-select --install
> ```
> 
> Thanks `brew doctor` for this hint.

Works for me. Reinstall CLT even if it's the latest version.
此方法有效。即使已经是最新的 CLT 了，也需要把文件夹删除干净后重新装，文件签名都是一样的。很诡异。
https://v2ex.com/t/725768

**Comment by nickolasdeluca** [comment]
> Another solution:
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> sudo xcode-select --install
> ```
> 
> Thanks `brew doctor` for this hint.

this saved my life, thank you kind user.

**Comment by CoolONEOfficial** [comment]
On last macOS beta you must install last CLT (`Command Line Tools for Xcode 12.3 beta 1`), CLT 12.2 didn't solve problem

**Comment by johnothwolo** [comment]
You don't have to reinstall anything, Just create an alias for MacOSX11.1.sdk. The SDKs are all symlinked to MacOSX.sdk. So this command is all you need.
`ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk`

AND

`ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk`


Apple has just really gotten sloppy lately at releasing software.

**Comment by petersonfs** [comment]
> Another solution:
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> sudo xcode-select --install
> ```
> 
> Thanks `brew doctor` for this hint.

I had the lastest version installed, but removing and installing again worked well.

**Comment by slimsheddy** [comment]
Downloading the Xcode 12.5 from developer.apple.com and then changing the CLT path via xcode helped me resolve the error brew was throwing. 

Previously:
![image](https://user-images.githubusercontent.com/6138906/120734560-6cd40800-c52c-11eb-973d-a773c33fad60.png)


![image](https://user-images.githubusercontent.com/6138906/120734452-3bf3d300-c52c-11eb-854e-23b808bd5d24.png)

After changing the path of CLT, I am on latest brew. 
![image](https://user-images.githubusercontent.com/6138906/120734703-ae64b300-c52c-11eb-87a2-1eaa1c9daeaa.png)
